---
Name: sharedraftcontent
After: framework/routes#coreroutes
---
SiteTree:
  extensions:
    - ShareDraftContentSiteTreeExtension
CMSMain:
  extensions:
    - ShareDraftContentRequirementsExtension
Controller:
  extensions:
    - ShareDraftContentControllerExtension
Director:
  rules:
    'preview': 'ShareDraftController'
